### ISSUE TITLE
sh not a function

### ISSUE THREAD

**Issue by selfagency** [rwu823/sh-exec#1]
after pulling the latest update from npm, my scripts started throwing `sh is not a function` errors. sample code:

```
const sh = require('sh-exec')

async function commit() {
  let spinner

  if (l) {
    return Promise.resolve()
  } else {
    spinner = ora('💾  Commiting changes ').start()
    try {
      await sh`
        git add . > /dev/null
        git commit -m "${m}" > /dev/null
        git push origin > /dev/null
      `
      spinner.succeed('💾  Committed and pushed changes ')
      return Promise.resolve()
    } catch (err) {
      spinner.fail('💾  Failed to commit changes ')
      return Promise.reject(err)
    }
  }
}
```

**Comment by rwu823** [comment]
Try to use this:

```js
const { default: sh }  = require('sh-exec')
```

I'll fix in next version.

**Comment by rwu823** [comment]
Try to use:

```js
const { default: sh } = require('sh-exec')
```

I'll fix this in next version.

**Comment by rwu823** [comment]
it should be worked fine in `v2.1.0`. 

https://repl.it/@rwu823/sh-exec

**Comment by selfagency** [comment]
works now, thanks
